title: "Luke Oliver"
description: "KCNA Certified | Computer Science Senior | Aspiring Platform Engineer"
author: Luke Oliver
url: "https://lukeoliver1776.github.io"
show_excerpts: false
github_username: lukeoliver1776
linkedin_url: "https://www.linkedin.com/in/luke-oliver-ga/"
email: "luke@oliver.us"
